# Generated by Django 4.2.27 on 2025-12-28 10:09

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short selling point (e.g., 'The ultimate Himalayan adventure')",
                        max_length=200,
                    ),
                ),
                (
                    "overview",
                    models.TextField(help_text="Brief introduction shown at the top"),
                ),
                (
                    "detailed_itinerary",
                    django_ckeditor_5.fields.CKEditor5Field(
                        help_text="Day-by-day itinerary with rich formatting"
                    ),
                ),
                (
                    "highlights",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, help_text="Key highlights and unique selling points"
                    ),
                ),
                (
                    "includes",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, help_text="What's included in the package"
                    ),
                ),
                (
                    "excludes",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, help_text="What's not included"
                    ),
                ),
                (
                    "essential_info",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, help_text="Important information, gear list, etc."
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("trek", "Trekking"),
                            ("expedition", "Expedition"),
                            ("tour", "Tour"),
                            ("climbing", "Peak Climbing"),
                        ],
                        default="trek",
                        max_length=20,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(help_text="Total duration in days"),
                ),
                (
                    "max_altitude",
                    models.PositiveIntegerField(help_text="Maximum altitude in meters"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("challenging", "Challenging"),
                            ("extreme", "Extreme"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "best_seasons",
                    models.JSONField(
                        blank=True, default=list, help_text='e.g., ["spring", "autumn"]'
                    ),
                ),
                ("group_size_min", models.PositiveIntegerField(default=1)),
                ("group_size_max", models.PositiveIntegerField(default=15)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Base price in USD", max_digits=10
                    ),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sale price (leave blank if no discount)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        help_text="Main hero image (recommended: 1920x1080)",
                        upload_to="trips/featured/",
                    ),
                ),
                (
                    "gallery",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of gallery image paths",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="YouTube or Vimeo embed URL"),
                ),
                (
                    "route_coordinates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="GeoJSON coordinates for route map",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (defaults to trip title)",
                        max_length=70,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO description (defaults to overview excerpt)",
                        max_length=160,
                    ),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True,
                        help_text="Primary keyword for SEO optimization",
                        max_length=100,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show on homepage featured section"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        help_text="Geographic region",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="core.region",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags for categorization and internal linking",
                        related_name="trips",
                        to="core.universaltag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
