# Generated by Django 4.2.27 on 2025-12-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="gallery",
        ),
        migrations.AlterField(
            model_name="trip",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Main hero image (recommended: 1920x1080)",
                null=True,
                upload_to="trips/featured/",
            ),
        ),
        migrations.CreateModel(
            name="TripGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Gallery image (recommended: 1200x800)",
                        upload_to="trips/gallery/",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility and SEO",
                        max_length=200,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
                "ordering": ["display_order", "id"],
            },
        ),
    ]
