# Generated by Django 4.2.27 on 2025-12-28 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("trips", "0002_remove_trip_gallery_alter_trip_featured_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="detailed_itinerary",
            field=models.TextField(
                help_text="Day-by-day itinerary with rich formatting (HTML supported)"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="essential_info",
            field=models.TextField(
                blank=True, help_text="Important information, gear list, etc."
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="excludes",
            field=models.TextField(blank=True, help_text="What's not included"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="highlights",
            field=models.TextField(
                blank=True, help_text="Key highlights and unique selling points"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="includes",
            field=models.TextField(
                blank=True, help_text="What's included in the package"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Geographic region",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips",
                to="core.region",
            ),
        ),
    ]
