# Generated by Django 4.2.27 on 2025-12-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_alter_trip_detailed_itinerary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="departure_location",
            field=models.CharField(
                blank=True,
                default="Kathmandu",
                help_text="Departure point",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="flight_duration_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total flight time in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="helicopter_capacity",
            field=models.PositiveIntegerField(
                blank=True,
                default=5,
                help_text="Maximum passengers per helicopter",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="landing_sites",
            field=models.TextField(
                blank=True,
                help_text="Landing locations (e.g., 'Kalapatthar, Everest Base Camp')",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_type",
            field=models.CharField(
                choices=[
                    ("trek", "Trekking"),
                    ("expedition", "Expedition"),
                    ("tour", "Tour"),
                    ("climbing", "Peak Climbing"),
                    ("helicopter", "Helicopter Tour"),
                ],
                default="trek",
                max_length=20,
            ),
        ),
    ]
