# Generated by Django 4.2.27 on 2025-12-28 10:09

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("team", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="content.blogcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short summary for previews and meta description",
                        max_length=300,
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        help_text="Main article content - supports Trip Card embedding"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("guide", "Travel Guide"),
                            ("story", "Trip Story"),
                            ("tips", "Tips & Advice"),
                            ("news", "News & Updates"),
                            ("gear", "Gear Review"),
                            ("culture", "Culture & History"),
                            ("safety", "Safety & Health"),
                        ],
                        default="guide",
                        max_length=20,
                    ),
                ),
                (
                    "read_time_minutes",
                    models.PositiveIntegerField(
                        default=5, help_text="Estimated reading time"
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        help_text="Main hero image (recommended: 1200x630 for social sharing)",
                        upload_to="blog/featured/",
                    ),
                ),
                (
                    "featured_image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility and SEO",
                        max_length=200,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (defaults to post title)",
                        max_length=70,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Meta description (defaults to excerpt)",
                        max_length=160,
                    ),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True,
                        help_text="Primary keyword for SEO optimization",
                        max_length=100,
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonical URL if republished from another source",
                    ),
                ),
                (
                    "schema_type",
                    models.CharField(
                        default="Article",
                        help_text="Schema.org type (Article, HowTo, FAQPage, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Pin to top of blog listing"
                    ),
                ),
                ("allow_comments", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Author for E-E-A-T compliance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_posts",
                        to="team.teammember",
                    ),
                ),
                (
                    "linked_trips",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Explicitly recommended trips shown in sidebar",
                        related_name="linked_by_blogs",
                        to="trips.trip",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary region this article covers",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blogposts",
                        to="core.region",
                    ),
                ),
                (
                    "related_tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags for categorization and internal linking",
                        related_name="blogposts",
                        to="core.universaltag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-is_featured", "-published_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-published_at"],
                        name="content_blo_status_b5b42b_idx",
                    ),
                    models.Index(
                        fields=["content_type", "status"],
                        name="content_blo_content_6a4919_idx",
                    ),
                ],
            },
        ),
    ]
