# Generated by Django 4.2.27 on 2025-12-28 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_remove_trip_gallery_alter_trip_featured_image_and_more"),
        ("team", "0001_initial"),
        ("core", "0001_initial"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
            },
        ),
        migrations.RemoveIndex(
            model_name="blogpost",
            name="content_blo_status_b5b42b_idx",
        ),
        migrations.RemoveIndex(
            model_name="blogpost",
            name="content_blo_content_6a4919_idx",
        ),
        migrations.RemoveField(
            model_name="blogcategory",
            name="display_order",
        ),
        migrations.RemoveField(
            model_name="blogcategory",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="blogcategory",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="allow_comments",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="featured_image_alt",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="read_time_minutes",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="schema_type",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="content.blogcategory",
            ),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="slug",
            field=models.SlugField(max_length=110, unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.ForeignKey(
                help_text="Author for E-E-A-T compliance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="team.teammember",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(help_text="Main content (HTML supported)"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("guide", "Travel Guide"),
                    ("story", "Travel Story"),
                    ("tips", "Tips & Advice"),
                    ("news", "News & Updates"),
                    ("gear", "Gear Reviews"),
                    ("culture", "Culture & History"),
                    ("safety", "Safety & Health"),
                ],
                default="guide",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="excerpt",
            field=models.TextField(
                help_text="Brief summary for listings and social sharing",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image (recommended: 1200x630)",
                upload_to="blog/featured/",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Feature on homepage or section headers"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="linked_trips",
            field=models.ManyToManyField(
                blank=True,
                help_text="Trips to feature as recommendations in this post",
                related_name="linked_by_blogs",
                to="trips.trip",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="SEO description (defaults to excerpt)",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Geographic region context",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_posts",
                to="core.region",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="related_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags for categorization (shared with trips)",
                related_name="blogposts",
                to="core.universaltag",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "In Review"),
                    ("published", "Published"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
