# Generated by Django 4.2.27 on 2025-12-28 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        help_text="Display name (e.g., 'Traverse The Himalayas')",
                        max_length=100,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, help_text="Short marketing tagline", max_length=200
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        help_text="Main logo (recommended: 200x60)",
                        upload_to="sites/logos/",
                    ),
                ),
                (
                    "logo_light",
                    models.ImageField(
                        blank=True,
                        help_text="Light version for dark backgrounds",
                        upload_to="sites/logos/",
                    ),
                ),
                ("favicon", models.ImageField(blank=True, upload_to="sites/favicons/")),
                (
                    "primary_color",
                    models.CharField(
                        default="#0369a1",
                        help_text="Primary brand color (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#0f766e",
                        help_text="Secondary brand color (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#f59e0b",
                        help_text="Accent/CTA color (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "target_segment",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("luxury", "Luxury"),
                            ("budget", "Budget"),
                            ("adventure", "Adventure"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        help_text="Default meta description for the site",
                        max_length=160,
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, help_text="Comma-separated keywords", max_length=255
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                (
                    "footer_text",
                    models.TextField(
                        blank=True, help_text="Additional footer text/disclaimer"
                    ),
                ),
                (
                    "copyright_name",
                    models.CharField(
                        blank=True, help_text="Copyright holder name", max_length=100
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, help_text="GA4 Measurement ID", max_length=50
                    ),
                ),
                ("facebook_pixel_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configurations",
            },
        ),
    ]
