# Generated by Django 4.2.27 on 2025-12-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_siteconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_description",
            field=models.TextField(
                blank=True, help_text="Footer brand description (shown below logo)"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_cta_text",
            field=models.CharField(
                default="Explore Trips",
                help_text="Hero call-to-action button text",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Homepage hero background",
                upload_to="sites/hero/",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_subtitle",
            field=models.TextField(
                blank=True, help_text="Homepage hero subtitle/description"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_title",
            field=models.CharField(
                blank=True,
                help_text="Homepage hero title (e.g., 'Discover Nepal')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="title_suffix",
            field=models.CharField(
                blank=True,
                help_text="Suffix for page titles (e.g., ' | NepalLuxe')",
                max_length=50,
            ),
        ),
    ]
