# Generated by Django 4.2.27 on 2025-12-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_siteconfiguration_footer_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to disable this site (shows maintenance page)",
            ),
        ),
    ]
