# Generated by Django 4.2.27 on 2025-12-28 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("guide", "Mountain Guide"),
                            ("author", "Content Writer"),
                            ("expert", "Subject Matter Expert"),
                            ("founder", "Founder"),
                        ],
                        default="author",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Professional title (e.g., 'Senior Trek Leader')",
                        max_length=100,
                    ),
                ),
                ("bio", models.TextField(help_text="Full biography for author page")),
                (
                    "short_bio",
                    models.CharField(
                        blank=True,
                        help_text="One-liner for author cards on blog posts",
                        max_length=200,
                    ),
                ),
                ("photo", models.ImageField(upload_to="team/")),
                (
                    "certifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of certifications, e.g., ["Certified Wilderness First Responder", "IFMGA Guide"]',
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Social links, e.g., {"linkedin": "url", "instagram": "url"}',
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=0, help_text="Years of experience in the industry"
                    ),
                ),
                (
                    "trips_led",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of trips/expeditions led"
                    ),
                ),
                (
                    "summits",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of successful summits"
                    ),
                ),
                (
                    "is_verified_expert",
                    models.BooleanField(
                        default=False,
                        help_text="Display 'Verified Expert' badge on posts",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional link to user account for login",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
