# Generated by Django 4.2.27 on 2025-12-28 10:09

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full term name (e.g., 'Acute Mountain Sickness')",
                        max_length=100,
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True, help_text="Short form (e.g., 'AMS')", max_length=20
                    ),
                ),
                (
                    "definition",
                    models.TextField(
                        help_text="Short definition (shown in tooltip/popup)"
                    ),
                ),
                (
                    "detailed_explanation",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Full content for the term's dedicated page",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "auto_link",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to auto-link this term in blog content",
                    ),
                ),
                (
                    "link_priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher priority terms are linked first (avoids conflicts)",
                    ),
                ),
                (
                    "max_links_per_page",
                    models.PositiveIntegerField(
                        default=3, help_text="Maximum times to link this term per page"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related content tags",
                        related_name="glossary_terms",
                        to="core.universaltag",
                    ),
                ),
                (
                    "related_terms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related glossary terms",
                        to="glossary.term",
                    ),
                ),
                (
                    "related_trips",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Trips where this term is relevant",
                        related_name="glossary_terms",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Glossary Term",
                "verbose_name_plural": "Glossary Terms",
                "ordering": ["name"],
            },
        ),
    ]
