# Generated by Django 4.2.27 on 2025-12-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("glossary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="abbreviation",
            field=models.CharField(
                blank=True,
                help_text="Short form (e.g., 'AMS' for 'Acute Mountain Sickness')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="auto_link",
            field=models.BooleanField(
                default=True, help_text="Automatically link this term in blog content"
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="definition",
            field=models.TextField(
                help_text="Brief definition (shown in tooltips and listings)"
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="detailed_explanation",
            field=models.TextField(
                blank=True, help_text="Detailed explanation (HTML supported)"
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="link_priority",
            field=models.PositiveIntegerField(
                default=5, help_text="Higher priority terms are linked first (1-10)"
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="term",
            name="related_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related topic tags",
                related_name="glossary_terms",
                to="core.universaltag",
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="slug",
            field=models.SlugField(max_length=110, unique=True),
        ),
    ]
